[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Only ship what you read in check-promo
[functions."check-promo"]
  included_files = [
    "data/discount_requests/**",
    "data/discount-requests/**"
  ]

[functions."check-promo-v2"]
  included_files = [
    "data/discount_requests/**",
    "data/discount-requests/**"
  ]
# --- Route exceptions (before the catch-all) ---
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/cart.html"
  status = 200

[[redirects]]
  from = "/enhanced-checkout"
  to = "/enhanced-checkout.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# --- SPA fallback for everything else ---
[[redirects]]
  from = "/*"
  to = "/error.html"
  status = 404
